### PR TITLE
Update to tip of upstream

### PR DESCRIPTION
**Pull request by alanking**
Still need to see if this builds for our supported platforms, so leaving as a draft for now

### CODE REVIEW

**Comment by alanking** [comment]
Tip of their master branch builds for ubuntu:22.04 and the sha currently in use by externals still exists, so I think we're good. @trel?

**Comment by alanking** [comment]
Alternatively, we can just start using the official repository using the git_repository key in versions.json for externals and we won't have to keep a mirror in Github.

**Comment by trel** [comment]
if we don't need to update, let's leave it as is.

we don't want to use the official repository - this repo/fork/mirror is a hedge against the internet moving / going away.

**Comment by alanking** [comment]
We do need to bring this up to speed to get the autoconf external on ubuntu:22.04

**Comment by trel** [comment]
So, ub22 does require a bump?   it won't/can't build the same/existing sha?

**Comment by alanking** [comment]
At the very least, we will have to adjust how we are building it, but I haven't dug into what would be required for that. Bumping it worked without making any other changes.

**Comment by trel** [comment]
@alanking, this was intentional?

**Comment by alanking** [comment]
Hmm... yes and no. :p I deleted my fork because autoconf was removed from externals: https://github.com/irods/externals/issues/186 I didn't really put together that it was going to close all the open PRs, but we don't really need these anymore.

**Comment by trel** [comment]
Got it.

**Pull request closed without merging**
